DATA:
    DIR: "data/SkiTB/"
    VAL_DIR: "data/SkiTB/"
    TEST_DIR: "data/SkiTB/"
    LABEL_FILE: "data/training/train_idx.txt"
    VAL_LABEL_FILE: "data/training/test_idx.txt"
    TEST_LABEL_FILE: "data/training/train_idx.txt"
    BATCH_SIZE: 8
    WORKERS: 4

OPTIMIZER:
    MOMENTUM: 0.9
    GAMMA: 0.1
    WEIGHT_DECAY: 0.001
    STEPS: []
    LR_START: 5e-3  #5e-3
    LR_END: 5e-4    #1e-3

MODEL:
    DH_DIMENTION: 100
    NUM_CONV_LAYER: 2
    NUM_POOL_LAYER: 2
    NUM_FC_LAYER: # This will enable the FC layer and disable the Pooling layer
    FIX: True
    THRESHOLD: 0.01
    EDGE_ALIGN: False
    BACKBONE: resnet50 
    # only support : resnet18, resnet50, resnet101, mobilenetv2, resnext50, res2net50, vgg16

TRAIN:
    EPOCHS: 60
    PRINT_FREQ: 40
    TEST: False
    SEED: 
    DATA_PARALLEL: True
    RESUME: 
    LOG_COMET: True
    SHOW_DATASET: False

MISC:
    TMP: "./model_output"
